// <auto-generated />
using System;
using ElysSalon2._0.adapters.OutBound.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElysSalon2._0.Migrations
{
    [DbContext(typeof(ElyDbContext))]
    [Migration("20250412211725_data-seeds-refactored2")]
    partial class dataseedsrefactored2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElysSalon2._0.Core.domain.Entities.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("ArticleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceBuy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ArticleId");

                    b.HasIndex("ArticleTypeId");

                    b.ToTable("Article");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            ArticleTypeId = 5,
                            Description = "MEESI",
                            Name = "Tinte Rojo",
                            PriceBuy = 12.59m,
                            PriceCost = 2.5m,
                            Stock = 10
                        },
                        new
                        {
                            ArticleId = 2,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Uñas Acrilicas",
                            PriceBuy = 22.59m,
                            PriceCost = 2.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 3,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Pedicure",
                            PriceBuy = 32.59m,
                            PriceCost = 2.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 4,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Manicure",
                            PriceBuy = 52.59m,
                            PriceCost = 1.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 5,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Corte Hombre",
                            PriceBuy = 5.5m,
                            PriceCost = 2.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 6,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Corte Mujer",
                            PriceBuy = 7.59m,
                            PriceCost = 3.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 7,
                            ArticleTypeId = 5,
                            Description = "MEESI",
                            Name = "Aritos",
                            PriceBuy = 32.59m,
                            PriceCost = 2.5m,
                            Stock = 15
                        },
                        new
                        {
                            ArticleId = 8,
                            ArticleTypeId = 5,
                            Description = "MEESI",
                            Name = "Pestañas",
                            PriceBuy = 52.59m,
                            PriceCost = 1.5m,
                            Stock = 10
                        },
                        new
                        {
                            ArticleId = 9,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Depilado Cejas",
                            PriceBuy = 42.59m,
                            PriceCost = 1.6m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 10,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Kersel",
                            PriceBuy = 65.59m,
                            PriceCost = 11.6m,
                            Stock = 21
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.Core.domain.Entities.ArticleType", b =>
                {
                    b.Property<int>("ArticleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleTypeId");

                    b.ToTable("ArticleType");

                    b.HasData(
                        new
                        {
                            ArticleTypeId = 1,
                            Name = "Todo"
                        },
                        new
                        {
                            ArticleTypeId = 2,
                            Name = "Elegir Tipo"
                        },
                        new
                        {
                            ArticleTypeId = 3,
                            Name = "Cabello"
                        },
                        new
                        {
                            ArticleTypeId = 4,
                            Name = "Servicio"
                        },
                        new
                        {
                            ArticleTypeId = 5,
                            Name = "Tintes"
                        },
                        new
                        {
                            ArticleTypeId = 6,
                            Name = "Producto"
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.Core.domain.Entities.Sales", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            SaleDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 48.50m
                        },
                        new
                        {
                            SaleId = 2,
                            SaleDate = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 77.30m
                        },
                        new
                        {
                            SaleId = 3,
                            SaleDate = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 65.90m
                        },
                        new
                        {
                            SaleId = 4,
                            SaleDate = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 92.40m
                        },
                        new
                        {
                            SaleId = 5,
                            SaleDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 58.75m
                        },
                        new
                        {
                            SaleId = 6,
                            SaleDate = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 84.20m
                        },
                        new
                        {
                            SaleId = 7,
                            SaleDate = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 41.00m
                        },
                        new
                        {
                            SaleId = 8,
                            SaleDate = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 95.10m
                        },
                        new
                        {
                            SaleId = 9,
                            SaleDate = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 38.60m
                        },
                        new
                        {
                            SaleId = 10,
                            SaleDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 87.90m
                        },
                        new
                        {
                            SaleId = 11,
                            SaleDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 63.35m
                        },
                        new
                        {
                            SaleId = 12,
                            SaleDate = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 55.20m
                        },
                        new
                        {
                            SaleId = 13,
                            SaleDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 70.45m
                        },
                        new
                        {
                            SaleId = 14,
                            SaleDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 39.99m
                        },
                        new
                        {
                            SaleId = 15,
                            SaleDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 99.00m
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.Core.domain.Entities.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EmissionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalOutTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalWithTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = "000200",
                            EmissionDateTime = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 19.99m
                        },
                        new
                        {
                            TicketId = "000201",
                            EmissionDateTime = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 25.75m
                        },
                        new
                        {
                            TicketId = "000202",
                            EmissionDateTime = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 31.20m
                        },
                        new
                        {
                            TicketId = "000203",
                            EmissionDateTime = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 16.80m
                        },
                        new
                        {
                            TicketId = "000204",
                            EmissionDateTime = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 22.50m
                        },
                        new
                        {
                            TicketId = "000205",
                            EmissionDateTime = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 38.70m
                        },
                        new
                        {
                            TicketId = "000206",
                            EmissionDateTime = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 26.10m
                        },
                        new
                        {
                            TicketId = "000207",
                            EmissionDateTime = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 20.00m
                        },
                        new
                        {
                            TicketId = "000208",
                            EmissionDateTime = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 35.00m
                        },
                        new
                        {
                            TicketId = "000209",
                            EmissionDateTime = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 24.40m
                        },
                        new
                        {
                            TicketId = "000210",
                            EmissionDateTime = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 28.50m
                        },
                        new
                        {
                            TicketId = "000211",
                            EmissionDateTime = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 36.60m
                        },
                        new
                        {
                            TicketId = "000212",
                            EmissionDateTime = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 18.90m
                        },
                        new
                        {
                            TicketId = "000213",
                            EmissionDateTime = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 30.00m
                        },
                        new
                        {
                            TicketId = "000214",
                            EmissionDateTime = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 21.75m
                        },
                        new
                        {
                            TicketId = "000215",
                            EmissionDateTime = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 37.80m
                        },
                        new
                        {
                            TicketId = "000216",
                            EmissionDateTime = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 15.60m
                        },
                        new
                        {
                            TicketId = "000217",
                            EmissionDateTime = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 17.25m
                        },
                        new
                        {
                            TicketId = "000218",
                            EmissionDateTime = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 33.50m
                        },
                        new
                        {
                            TicketId = "000219",
                            EmissionDateTime = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 29.90m
                        },
                        new
                        {
                            TicketId = "000220",
                            EmissionDateTime = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 36.20m
                        },
                        new
                        {
                            TicketId = "000221",
                            EmissionDateTime = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 19.20m
                        },
                        new
                        {
                            TicketId = "000222",
                            EmissionDateTime = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 38.50m
                        },
                        new
                        {
                            TicketId = "000223",
                            EmissionDateTime = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 27.30m
                        },
                        new
                        {
                            TicketId = "000224",
                            EmissionDateTime = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 34.80m
                        },
                        new
                        {
                            TicketId = "000225",
                            EmissionDateTime = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 32.40m
                        },
                        new
                        {
                            TicketId = "000226",
                            EmissionDateTime = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 18.45m
                        },
                        new
                        {
                            TicketId = "000227",
                            EmissionDateTime = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 20.35m
                        },
                        new
                        {
                            TicketId = "000228",
                            EmissionDateTime = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 15.99m
                        },
                        new
                        {
                            TicketId = "000229",
                            EmissionDateTime = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 39.00m
                        },
                        new
                        {
                            TicketId = "000230",
                            EmissionDateTime = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 26.60m
                        },
                        new
                        {
                            TicketId = "000231",
                            EmissionDateTime = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 22.80m
                        },
                        new
                        {
                            TicketId = "000232",
                            EmissionDateTime = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 31.90m
                        },
                        new
                        {
                            TicketId = "000233",
                            EmissionDateTime = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 38.00m
                        },
                        new
                        {
                            TicketId = "000234",
                            EmissionDateTime = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 35.75m
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.Core.domain.Entities.TicketDetails", b =>
                {
                    b.Property<int>("TicketDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketDetailsId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TicketDetailsId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketDetails");
                });

            modelBuilder.Entity("ElysSalon2._0.Core.domain.Entities.Article", b =>
                {
                    b.HasOne("ElysSalon2._0.Core.domain.Entities.ArticleType", "ArticleType")
                        .WithMany()
                        .HasForeignKey("ArticleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleType");
                });

            modelBuilder.Entity("ElysSalon2._0.Core.domain.Entities.TicketDetails", b =>
                {
                    b.HasOne("ElysSalon2._0.Core.domain.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElysSalon2._0.Core.domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketDetails")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ElysSalon2._0.Core.domain.Entities.Ticket", b =>
                {
                    b.Navigation("TicketDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
