// <auto-generated />
using System;
using ElysSalon2._0.adapters.OutBound.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElysSalon2._0.Migrations
{
    [DbContext(typeof(ElyDbContext))]
    [Migration("20250514193937_dataSeedAdded")]
    partial class dataSeedAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElysSalon2._0.domain.Entities.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("ArticleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceBuy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ArticleId");

                    b.HasIndex("ArticleTypeId");

                    b.ToTable("Article");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            ArticleTypeId = 5,
                            Description = "MEESI",
                            Name = "Tinte Rojo",
                            PriceBuy = 12.59m,
                            PriceCost = 2.5m,
                            Stock = 10
                        },
                        new
                        {
                            ArticleId = 2,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Uñas Acrilicas",
                            PriceBuy = 22.59m,
                            PriceCost = 2.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 3,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Pedicure",
                            PriceBuy = 32.59m,
                            PriceCost = 2.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 4,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Manicure",
                            PriceBuy = 52.59m,
                            PriceCost = 1.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 5,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Corte Hombre",
                            PriceBuy = 5.5m,
                            PriceCost = 2.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 6,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Corte Mujer",
                            PriceBuy = 7.59m,
                            PriceCost = 3.5m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 7,
                            ArticleTypeId = 5,
                            Description = "MEESI",
                            Name = "Aritos",
                            PriceBuy = 32.59m,
                            PriceCost = 2.5m,
                            Stock = 15
                        },
                        new
                        {
                            ArticleId = 8,
                            ArticleTypeId = 5,
                            Description = "MEESI",
                            Name = "Pestañas",
                            PriceBuy = 52.59m,
                            PriceCost = 1.5m,
                            Stock = 10
                        },
                        new
                        {
                            ArticleId = 9,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Depilado Cejas",
                            PriceBuy = 42.59m,
                            PriceCost = 1.6m,
                            Stock = 1
                        },
                        new
                        {
                            ArticleId = 10,
                            ArticleTypeId = 3,
                            Description = "MEESI",
                            Name = "Kersel",
                            PriceBuy = 65.59m,
                            PriceCost = 11.6m,
                            Stock = 21
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.domain.Entities.ArticleType", b =>
                {
                    b.Property<int>("ArticleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleTypeId");

                    b.ToTable("ArticleType");

                    b.HasData(
                        new
                        {
                            ArticleTypeId = 1,
                            Name = "Todo"
                        },
                        new
                        {
                            ArticleTypeId = 2,
                            Name = "Elegir Tipo"
                        },
                        new
                        {
                            ArticleTypeId = 3,
                            Name = "Cabello"
                        },
                        new
                        {
                            ArticleTypeId = 4,
                            Name = "Servicio"
                        },
                        new
                        {
                            ArticleTypeId = 5,
                            Name = "Tintes"
                        },
                        new
                        {
                            ArticleTypeId = 6,
                            Name = "Producto"
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expense");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 25.50m,
                            Date = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Compra de suministros"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 15.75m,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Almuerzo"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 80.00m,
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Combustible"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 35.20m,
                            Date = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Reparación menor"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 12.99m,
                            Date = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Suscripción online"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 210.50m,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Viaje de negocios"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 45.00m,
                            Date = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Material de oficina"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 65.80m,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Pago de internet"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 200.00m,
                            Date = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Alquiler de local"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 90.30m,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Curso online"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 18.75m,
                            Date = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Mantenimiento web"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 75.00m,
                            Date = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Publicidad Facebook"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 5.50m,
                            Date = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Impresiones"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 30.25m,
                            Date = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Productos de limpieza"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 40.00m,
                            Date = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Soporte técnico"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 150.00m,
                            Date = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Licencia de software"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 55.60m,
                            Date = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Seguro"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 12.30m,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Envío de documentos"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 300.00m,
                            Date = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Consultoría"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 85.40m,
                            Date = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Entrada a evento"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 28.90m,
                            Date = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Suministros varios"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 18.50m,
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Cafetería"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 95.00m,
                            Date = new DateTime(2025, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Mantenimiento vehículo"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 42.15m,
                            Date = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Arreglo de oficina"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 7.99m,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "App de productividad"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 180.75m,
                            Date = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Alojamiento"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 38.20m,
                            Date = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Papelería"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 70.50m,
                            Date = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Pago de agua"
                        },
                        new
                        {
                            Id = 29,
                            Amount = 100.00m,
                            Date = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Publicidad impresa"
                        },
                        new
                        {
                            Id = 30,
                            Amount = 105.60m,
                            Date = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Seminario"
                        },
                        new
                        {
                            Id = 31,
                            Amount = 22.40m,
                            Date = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Actualización web"
                        },
                        new
                        {
                            Id = 32,
                            Amount = 88.00m,
                            Date = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Google Ads"
                        },
                        new
                        {
                            Id = 33,
                            Amount = 9.20m,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Fotocopias"
                        },
                        new
                        {
                            Id = 34,
                            Amount = 33.90m,
                            Date = new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Material de aseo"
                        },
                        new
                        {
                            Id = 35,
                            Amount = 58.15m,
                            Date = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Repuestos"
                        },
                        new
                        {
                            Id = 36,
                            Amount = 165.00m,
                            Date = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Software contable"
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.domain.Entities.Sales", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 100,
                            SaleDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 20.50m
                        },
                        new
                        {
                            SaleId = 101,
                            SaleDate = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 59.30m
                        },
                        new
                        {
                            SaleId = 102,
                            SaleDate = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 10.50m
                        },
                        new
                        {
                            SaleId = 103,
                            SaleDate = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 23.70m
                        },
                        new
                        {
                            SaleId = 104,
                            SaleDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 56.40m
                        },
                        new
                        {
                            SaleId = 105,
                            SaleDate = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 60.00m
                        },
                        new
                        {
                            SaleId = 106,
                            SaleDate = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 65.10m
                        },
                        new
                        {
                            SaleId = 107,
                            SaleDate = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 13.30m
                        },
                        new
                        {
                            SaleId = 108,
                            SaleDate = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 27.00m
                        },
                        new
                        {
                            SaleId = 109,
                            SaleDate = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 34.90m
                        },
                        new
                        {
                            SaleId = 110,
                            SaleDate = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 80.10m
                        },
                        new
                        {
                            SaleId = 111,
                            SaleDate = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 28.20m
                        },
                        new
                        {
                            SaleId = 112,
                            SaleDate = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 77.40m
                        },
                        new
                        {
                            SaleId = 113,
                            SaleDate = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 66.90m
                        },
                        new
                        {
                            SaleId = 114,
                            SaleDate = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 97.50m
                        },
                        new
                        {
                            SaleId = 115,
                            SaleDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 69.90m
                        },
                        new
                        {
                            SaleId = 116,
                            SaleDate = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 66.45m
                        },
                        new
                        {
                            SaleId = 117,
                            SaleDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 60.10m
                        },
                        new
                        {
                            SaleId = 118,
                            SaleDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 50.40m
                        },
                        new
                        {
                            SaleId = 119,
                            SaleDate = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 49.40m
                        },
                        new
                        {
                            SaleId = 120,
                            SaleDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 38.50m
                        },
                        new
                        {
                            SaleId = 122,
                            SaleDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 80.10m
                        },
                        new
                        {
                            SaleId = 123,
                            SaleDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 110.40m
                        },
                        new
                        {
                            SaleId = 124,
                            SaleDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 119.40m
                        },
                        new
                        {
                            SaleId = 125,
                            SaleDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 63.50m
                        },
                        new
                        {
                            SaleId = 126,
                            SaleDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 57.42m
                        },
                        new
                        {
                            SaleId = 127,
                            SaleDate = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 50.40m
                        },
                        new
                        {
                            SaleId = 128,
                            SaleDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 49.40m
                        },
                        new
                        {
                            SaleId = 129,
                            SaleDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 38.50m
                        },
                        new
                        {
                            SaleId = 130,
                            SaleDate = new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 80.10m
                        },
                        new
                        {
                            SaleId = 131,
                            SaleDate = new DateTime(2025, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 110.40m
                        },
                        new
                        {
                            SaleId = 132,
                            SaleDate = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 119.40m
                        },
                        new
                        {
                            SaleId = 133,
                            SaleDate = new DateTime(2025, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 63.50m
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.domain.Entities.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EmissionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalOutTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalWithTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = "001100",
                            EmissionDateTime = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 18.50m
                        },
                        new
                        {
                            TicketId = "001101",
                            EmissionDateTime = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 22.30m
                        },
                        new
                        {
                            TicketId = "001102",
                            EmissionDateTime = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 19.70m
                        },
                        new
                        {
                            TicketId = "001103",
                            EmissionDateTime = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 24.10m
                        },
                        new
                        {
                            TicketId = "001104",
                            EmissionDateTime = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 25.20m
                        },
                        new
                        {
                            TicketId = "001105",
                            EmissionDateTime = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 30.50m
                        },
                        new
                        {
                            TicketId = "001106",
                            EmissionDateTime = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 27.80m
                        },
                        new
                        {
                            TicketId = "001107",
                            EmissionDateTime = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 15.90m
                        },
                        new
                        {
                            TicketId = "001108",
                            EmissionDateTime = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 36.40m
                        },
                        new
                        {
                            TicketId = "001109",
                            EmissionDateTime = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 22.10m
                        },
                        new
                        {
                            TicketId = "001110",
                            EmissionDateTime = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 17.90m
                        },
                        new
                        {
                            TicketId = "001111",
                            EmissionDateTime = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 35.10m
                        },
                        new
                        {
                            TicketId = "001112",
                            EmissionDateTime = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 23.30m
                        },
                        new
                        {
                            TicketId = "001113",
                            EmissionDateTime = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 31.25m
                        },
                        new
                        {
                            TicketId = "001114",
                            EmissionDateTime = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 25.75m
                        },
                        new
                        {
                            TicketId = "001115",
                            EmissionDateTime = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 38.90m
                        },
                        new
                        {
                            TicketId = "001116",
                            EmissionDateTime = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 18.60m
                        },
                        new
                        {
                            TicketId = "001117",
                            EmissionDateTime = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 17.40m
                        },
                        new
                        {
                            TicketId = "001118",
                            EmissionDateTime = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 16.10m
                        },
                        new
                        {
                            TicketId = "001119",
                            EmissionDateTime = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 12.30m
                        },
                        new
                        {
                            TicketId = "001120",
                            EmissionDateTime = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 31.90m
                        },
                        new
                        {
                            TicketId = "001121",
                            EmissionDateTime = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 11.60m
                        },
                        new
                        {
                            TicketId = "001122",
                            EmissionDateTime = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 21.80m
                        },
                        new
                        {
                            TicketId = "001123",
                            EmissionDateTime = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 11.90m
                        },
                        new
                        {
                            TicketId = "001124",
                            EmissionDateTime = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 21.50m
                        },
                        new
                        {
                            TicketId = "001125",
                            EmissionDateTime = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 21.80m
                        },
                        new
                        {
                            TicketId = "001126",
                            EmissionDateTime = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 42.10m
                        },
                        new
                        {
                            TicketId = "001127",
                            EmissionDateTime = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 36.45m
                        },
                        new
                        {
                            TicketId = "001128",
                            EmissionDateTime = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 15.10m
                        },
                        new
                        {
                            TicketId = "001129",
                            EmissionDateTime = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 24.80m
                        },
                        new
                        {
                            TicketId = "001130",
                            EmissionDateTime = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 12.60m
                        },
                        new
                        {
                            TicketId = "001131",
                            EmissionDateTime = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 22.40m
                        },
                        new
                        {
                            TicketId = "001132",
                            EmissionDateTime = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 34.50m
                        },
                        new
                        {
                            TicketId = "001133",
                            EmissionDateTime = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 24.80m
                        },
                        new
                        {
                            TicketId = "001134",
                            EmissionDateTime = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 12.60m
                        },
                        new
                        {
                            TicketId = "001135",
                            EmissionDateTime = new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 22.40m
                        },
                        new
                        {
                            TicketId = "001136",
                            EmissionDateTime = new DateTime(2025, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 34.50m
                        },
                        new
                        {
                            TicketId = "001137",
                            EmissionDateTime = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "",
                            TotalAmount = 34.50m
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.domain.Entities.TicketDetails", b =>
                {
                    b.Property<int>("TicketDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketDetailsId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TicketDetailsId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketDetails");

                    b.HasData(
                        new
                        {
                            TicketDetailsId = 422,
                            ArticleId = 5,
                            ArticleName = "Tinte Rojo",
                            Date = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 423,
                            ArticleId = 5,
                            ArticleName = "Tinte Rojo",
                            Date = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 424,
                            ArticleId = 5,
                            ArticleName = "Desde un Mes",
                            Date = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 425,
                            ArticleId = 5,
                            ArticleName = "Desde hace 3 meses",
                            Date = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 426,
                            ArticleId = 6,
                            ArticleName = "Desde un Mes",
                            Date = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 427,
                            ArticleId = 9,
                            ArticleName = "Desde hace 3 meses",
                            Date = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 428,
                            ArticleId = 4,
                            ArticleName = "Desde hace 3 meses",
                            Date = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 429,
                            ArticleId = 9,
                            ArticleName = "Desde hace 3 meses",
                            Date = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 430,
                            ArticleId = 7,
                            ArticleName = "Desde hace 3 meses",
                            Date = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 431,
                            ArticleId = 7,
                            ArticleName = "Desde hace 1 mes",
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        },
                        new
                        {
                            TicketDetailsId = 432,
                            ArticleId = 7,
                            ArticleName = "Desde hace 3 meses",
                            Date = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Price = 12.59m,
                            Quantity = 1,
                            TicketId = "001100"
                        });
                });

            modelBuilder.Entity("ElysSalon2._0.domain.Entities.Article", b =>
                {
                    b.HasOne("ElysSalon2._0.domain.Entities.ArticleType", "ArticleType")
                        .WithMany()
                        .HasForeignKey("ArticleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleType");
                });

            modelBuilder.Entity("ElysSalon2._0.domain.Entities.TicketDetails", b =>
                {
                    b.HasOne("ElysSalon2._0.domain.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElysSalon2._0.domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketDetails")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ElysSalon2._0.domain.Entities.Ticket", b =>
                {
                    b.Navigation("TicketDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
